language: cpp

#
# We need a more recent version of GCC to build.
#
addons:
 apt:
   sources:
   - ubuntu-toolchain-r-test
   packages:
   - gcc-4.8
   - g++-4.8

before_install:
  - SEEC_LLVM_RELEASE_TAG="v3.9.0"
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi

# 
# LLVM needs a more recent version of CMake. This code comes from the following
# answer about installing an updated CMake:
#   http://stackoverflow.com/a/33203355
#
install:
  - DEPS_DIR="${TRAVIS_BUILD_DIR}/deps"
  - DEPS_INSTALL="${DEPS_DIR}/install"
  - mkdir -p ${DEPS_DIR}
  - mkdir -p ${DEPS_INSTALL}
  - cd ${DEPS_DIR}
  - |
    if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then
      CMAKE_URL="http://www.cmake.org/files/v3.4/cmake-3.4.3-Linux-x86_64.tar.gz"
      mkdir cmake && travis_retry wget --no-check-certificate --quiet -O - ${CMAKE_URL} | tar --strip-components=1 -xz -C cmake
      export PATH=${DEPS_DIR}/cmake/bin:${PATH}
    fi
#
# Download pre-built LLVM.
#
  - |
    cd ${DEPS_INSTALL}
    if [ ! -d "include/llvm" ]; then
      SEEC_LLVM_BUILT_XZ_FILENAME="seec_llvm_travis_build_${TRAVIS_OS_NAME}_${CC}.tar.xz"
      travis_retry wget --no-check-certificate --quiet -O - https://github.com/seec-team/llvm-with-seec-clang/releases/download/${SEEC_LLVM_RELEASE_TAG}/${SEEC_LLVM_BUILT_XZ_FILENAME} | tar -xJ
    fi

#
# Generate build scripts using CMake. We configure SeeC-Clang as an external
# project that uses the downloaded (prebuilt) LLVM.
#
before_script:
  - cd ${TRAVIS_BUILD_DIR}
  - mkdir seec-build
  - cd seec-build
  - cmake -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Release -DLLVM_INCLUDE_TESTS=off -DCMAKE_PROGRAM_PATH=${DEPS_INSTALL}/bin/ -DCMAKE_INSTALL_PREFIX=${TRAVIS_BUILD_DIR}/seec-clang-install ${TRAVIS_BUILD_DIR}

#
# Build using the makefiles previously generated by CMake.
#
script:
  - cd ${TRAVIS_BUILD_DIR}/seec-build
  - make -j2

#
# Install, then compress the install directory for deployment.
#
after_success:
  - |
    mkdir -p ${TRAVIS_BUILD_DIR}/seec-clang-install
    cd ${TRAVIS_BUILD_DIR}/seec-build
    make install
    cd ${TRAVIS_BUILD_DIR}
    SEEC_BUILT_XZ_FILENAME="seec_clang_travis_build_${TRAVIS_OS_NAME}_${CC}.tar.xz"
    tar -cJf ${TRAVIS_BUILD_DIR}/${SEEC_BUILT_XZ_FILENAME} -C ${TRAVIS_BUILD_DIR}/seec-clang-install .

matrix:
  include:
    - os: linux
      compiler: clang
    - os: linux
      compiler: gcc
    - os: osx
      compiler: clang

#
# For tagged releases, push the compressed install directory to GitHub.
#
deploy:
  provider: releases
  api_key:
    secure: c+WV2+zKZNtzuhbtH16cnBtDd467IkPJ10sRhQcb7AUfMSHlK2FeJrA8MFw/dFJ0/tmrqYzb4apkZGFQPphU22ZDsZj6tE2bnHDFz1viyMuV/4SRHiqSm5/yJw8S+bNAhNYz7U3g+0Y1+vhqbg4bD+xPM/chIYyf5kVu2nNjCnScmFSVSOH0h9TSmUB4ipdUB9XHA5akO6uCfKR8UMTV9jKyN7ZfUs5lruaPfWXEKP+BdkB1lrB3STyUh6VUpX+do7VlbAOt7AhhRxcZmgXp1ZuNJso9QPpnfoRAQSaxkVijbYljOxz6FHaQqxSTMfrVdWGHsHqLveAbDAQmbsBVw6v5KSMXxSycZanA8djWGxpdaJYRlXyVfsg5bgqta+/db54Cwj2gowGGuC35cPxSqrB2Nt5OpWi/3xahP3YTGY9ZJOMx+nE2GVcqb3tPVS1/CV2mHtSWgrWNQSkCC5F72fi8lkh3c1N3El1ovNCWCJYIiaQ0b2kpbWaBI8z6lnS7bB7X3H2BfCWrkbKApZuzFmAVA9YDcDvSCloU/Oy2lVLVd3OhCmLmFDvJQJjehH8PkWLCl+qrDvMufnvOTBmyRkrWjc6M9uwxFvOIqWBx0ankxrRBaiIlzjt6XqhxuVkI2T0qTjuBfQWS8TH1uObXDzxDtXfcyLVZD13GSOlfBPc=
  file: "${TRAVIS_BUILD_DIR}/${SEEC_BUILT_XZ_FILENAME}"
  skip_cleanup: true
  on:
    tags: true
    repo: seec-team/seec-clang

