language: cpp

matrix:
  include:
    - os: linux
      dist: trusty
      compiler: clang
      env: 
        - COMPILER_CXX=clang++
        - COMPILER_CC=clang
        - SEEC_LLVM_BUILT_XZ_FILENAME="seec_llvm_travis_build_linux_clang.tar.xz"
    - os: linux
      dist: trusty
      compiler: clang
      addons:
        apt:
          sources:
          - llvm-toolchain-trusty-4.0
          packages:
          - clang-4.0
      env: 
        - COMPILER_CXX=clang++-4.0
        - COMPILER_CC=clang-4.0
        - SEEC_LLVM_BUILT_XZ_FILENAME="seec_llvm_travis_build_linux_clang.tar.xz"
    - os: linux
      dist: trusty
      compiler: gcc
      addons:
        apt:
          sources:
          - ubuntu-toolchain-r-test
          packages:
          - gcc-6
          - g++-6
      env:
        - COMPILER_CXX=g++-6
        - COMPILER_CC=gcc-6
        - SEEC_LLVM_BUILT_XZ_FILENAME="seec_llvm_travis_build_linux_gcc.tar.xz"
    - os: linux
      dist: trusty
      compiler: gcc
      addons:
        apt:
          sources:
          - ubuntu-toolchain-r-test
          packages:
          - gcc-7
          - g++-7
      env:
        - COMPILER_CXX=g++-7
        - COMPILER_CC=gcc-7
        - SEEC_LLVM_BUILT_XZ_FILENAME="seec_llvm_travis_build_linux_gcc.tar.xz"
    - os: osx
      osx_image: xcode7.3
      compiler: clang
      env: 
        - THE_OSX_IMAGE=xcode7.3
        - COMPILER_CXX=clang++
        - COMPILER_CC=clang
    - os: osx
      osx_image: xcode9
      compiler: clang
      env: 
        - THE_OSX_IMAGE=xcode9
        - COMPILER_CXX=clang++
        - COMPILER_CC=clang

before_install:
  - SEEC_LLVM_RELEASE_TAG="v6.0"
  - export CXX="${COMPILER_CXX}" CC="${COMPILER_CC}"

# 
# LLVM needs a more recent version of CMake. This code comes from the following
# answer about installing an updated CMake:
#   http://stackoverflow.com/a/33203355
#
install:
  - DEPS_DIR="${TRAVIS_BUILD_DIR}/deps"
  - DEPS_INSTALL="${DEPS_DIR}/install"
  - mkdir -p ${DEPS_DIR}
  - mkdir -p ${DEPS_INSTALL}
  - cd ${DEPS_DIR}
  - |
    if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then
      CMAKE_URL="http://www.cmake.org/files/v3.4/cmake-3.4.3-Linux-x86_64.tar.gz"
      mkdir cmake && travis_retry wget --no-check-certificate --quiet -O - ${CMAKE_URL} | tar --strip-components=1 -xz -C cmake
      export PATH=${DEPS_DIR}/cmake/bin:${PATH}
    fi
    CMAKE_GENERATOR="Unix Makefiles"
    EXTRA_CMAKE_ARGUMENTS=""
    CMAKE_BUILD_COMMAND="make -j3"
#
# Download pre-built LLVM.
#
  - |
    cd ${DEPS_INSTALL}
    if [ ! -d "include/llvm" ]; then
      if [[ "${TRAVIS_OS_NAME}" == "osx" ]]; then
        SEEC_LLVM_BUILT_XZ_FILENAME="seec_llvm_travis_build_${TRAVIS_OS_NAME}_${THE_OSX_IMAGE}_${CC}.tar.xz"
      fi
      travis_retry wget --no-check-certificate --quiet -O - https://github.com/seec-team/llvm-with-seec-clang/releases/download/${SEEC_LLVM_RELEASE_TAG}/${SEEC_LLVM_BUILT_XZ_FILENAME} | tar -xJ
    fi

#
# Generate build scripts using CMake. We configure SeeC-Clang as an external
# project that uses the downloaded (prebuilt) LLVM.
#
before_script:
  - cd ${TRAVIS_BUILD_DIR}
  - mkdir seec-build
  - cd seec-build
  - cmake -G "${CMAKE_GENERATOR}" ${EXTRA_CMAKE_ARGUMENTS} -DCMAKE_BUILD_TYPE=Release -DLLVM_ENABLE_EH=true -DLLVM_ENABLE_PIC=true -DLLVM_ENABLE_RTTI=true -DLLVM_INCLUDE_TESTS=off -DCLANG_BUILD_TOOLS=off -DCLANG_ENABLE_ARCMT=off -DCLANG_ENABLE_STATIC_ANALYZER=off -DCLANG_INCLUDE_TESTS=off -DCMAKE_PROGRAM_PATH=${DEPS_INSTALL}/bin/ -DLLVM_CONFIG=${DEPS_INSTALL}/bin/llvm-config -DCMAKE_INSTALL_PREFIX=${TRAVIS_BUILD_DIR}/seec-clang-install ${TRAVIS_BUILD_DIR}

#
# Build using the makefiles previously generated by CMake.
#
script:
  - cd ${TRAVIS_BUILD_DIR}/seec-build
  - ${CMAKE_BUILD_COMMAND}

#
# Install, then compress the install directory for deployment.
#
after_success:
  - |
    mkdir -p ${TRAVIS_BUILD_DIR}/seec-clang-install
    cd ${TRAVIS_BUILD_DIR}/seec-build
    cmake --build . --target install
    cd ${TRAVIS_BUILD_DIR}
    if [[ "${TRAVIS_OS_NAME}" == "osx" ]]; then
      SEEC_BUILT_XZ_FILENAME="seec_clang_travis_build_${TRAVIS_OS_NAME}_${THE_OSX_IMAGE}_${CC}.tar.xz"
    else
      SEEC_BUILT_XZ_FILENAME="seec_clang_travis_build_${TRAVIS_OS_NAME}_${CC}.tar.xz"
    fi
    tar -cJf ${TRAVIS_BUILD_DIR}/${SEEC_BUILT_XZ_FILENAME} -C ${TRAVIS_BUILD_DIR}/seec-clang-install .

#
# For tagged releases, push the compressed install directory to GitHub.
#
deploy:
  provider: releases
  api_key:
    secure: c+WV2+zKZNtzuhbtH16cnBtDd467IkPJ10sRhQcb7AUfMSHlK2FeJrA8MFw/dFJ0/tmrqYzb4apkZGFQPphU22ZDsZj6tE2bnHDFz1viyMuV/4SRHiqSm5/yJw8S+bNAhNYz7U3g+0Y1+vhqbg4bD+xPM/chIYyf5kVu2nNjCnScmFSVSOH0h9TSmUB4ipdUB9XHA5akO6uCfKR8UMTV9jKyN7ZfUs5lruaPfWXEKP+BdkB1lrB3STyUh6VUpX+do7VlbAOt7AhhRxcZmgXp1ZuNJso9QPpnfoRAQSaxkVijbYljOxz6FHaQqxSTMfrVdWGHsHqLveAbDAQmbsBVw6v5KSMXxSycZanA8djWGxpdaJYRlXyVfsg5bgqta+/db54Cwj2gowGGuC35cPxSqrB2Nt5OpWi/3xahP3YTGY9ZJOMx+nE2GVcqb3tPVS1/CV2mHtSWgrWNQSkCC5F72fi8lkh3c1N3El1ovNCWCJYIiaQ0b2kpbWaBI8z6lnS7bB7X3H2BfCWrkbKApZuzFmAVA9YDcDvSCloU/Oy2lVLVd3OhCmLmFDvJQJjehH8PkWLCl+qrDvMufnvOTBmyRkrWjc6M9uwxFvOIqWBx0ankxrRBaiIlzjt6XqhxuVkI2T0qTjuBfQWS8TH1uObXDzxDtXfcyLVZD13GSOlfBPc=
  file: "${TRAVIS_BUILD_DIR}/${SEEC_BUILT_XZ_FILENAME}"
  skip_cleanup: true
  on:
    tags: true
    repo: seec-team/seec-clang

