language: cpp

#
# We need a more recent version of GCC to build.
#
addons:
 apt:
   sources:
   - ubuntu-toolchain-r-test
   packages:
   - gcc-4.8
   - g++-4.8

before_install:
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi

# 
# LLVM needs a more recent version of CMake. This code comes from the following
# answer about installing an updated CMake:
#   http://stackoverflow.com/a/33203355
#
install:
  - DEPS_DIR="${TRAVIS_BUILD_DIR}/deps"
  - mkdir ${DEPS_DIR} && cd ${DEPS_DIR}
  - |
    if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then
      CMAKE_URL="http://www.cmake.org/files/v3.4/cmake-3.4.3-Linux-x86_64.tar.gz"
      mkdir cmake && travis_retry wget --no-check-certificate --quiet -O - ${CMAKE_URL} | tar --strip-components=1 -xz -C cmake
      export PATH=${DEPS_DIR}/cmake/bin:${PATH}
    fi

#
# Before we can build, we need to download the source code for the matching
# LLVM release, link SeeC-Clang's source into the correct directory, and then
# generate the build scripts using CMake.
#
before_script:
  - wget http://llvm.org/releases/3.9.0/llvm-3.9.0.src.tar.xz -O /tmp/llvm.tar.xz
  - cd ${TRAVIS_BUILD_DIR}
  - tar -xf /tmp/llvm.tar.xz
  - ln -s ${TRAVIS_BUILD_DIR} llvm-3.9.0.src/tools/clang
  - mkdir seec-build
  - cd seec-build
  - cmake -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Release -DLLVM_TARGETS_TO_BUILD="host" -DLLVM_BUILD_TOOLS=false -DLLVM_INCLUDE_TESTS=false -DCLANG_BUILD_TOOLS=false -DLLVM_ENABLE_EH=true -DLLVM_ENABLE_PIC=true -DLLVM_ENABLE_RTTI=true -DCMAKE_INSTALL_PREFIX=${TRAVIS_BUILD_DIR}/llvm+seec-clang-install ${TRAVIS_BUILD_DIR}/llvm-3.9.0.src/

#
# Build using the makefiles previously generated by CMake.
#
script:
  - cd ${TRAVIS_BUILD_DIR}/seec-build
  - make -j2

#
# Install, then compress the install directory for deployment.
#
after_success:
  - |
    mkdir -p ${TRAVIS_BUILD_DIR}/llvm+seec-clang-install
    cd ${TRAVIS_BUILD_DIR}/seec-build
    make install
    cd ${TRAVIS_BUILD_DIR}
    SEEC_BUILT_XZ_FILENAME="seec_clang_travis_build_${TRAVIS_OS_NAME}_${CC}.tar.xz"
    tar -cJf ${TRAVIS_BUILD_DIR}/${SEEC_BUILT_XZ_FILENAME} -C ${TRAVIS_BUILD_DIR}/llvm+seec-clang-install .

matrix:
  include:
    - os: linux
      compiler: clang
    - os: linux
      compiler: gcc
    - os: osx
      compiler: clang

#
# For tagged releases, push the compressed install directory to GitHub.
#
deploy:
  provider: releases
  api_key:
    secure: c+WV2+zKZNtzuhbtH16cnBtDd467IkPJ10sRhQcb7AUfMSHlK2FeJrA8MFw/dFJ0/tmrqYzb4apkZGFQPphU22ZDsZj6tE2bnHDFz1viyMuV/4SRHiqSm5/yJw8S+bNAhNYz7U3g+0Y1+vhqbg4bD+xPM/chIYyf5kVu2nNjCnScmFSVSOH0h9TSmUB4ipdUB9XHA5akO6uCfKR8UMTV9jKyN7ZfUs5lruaPfWXEKP+BdkB1lrB3STyUh6VUpX+do7VlbAOt7AhhRxcZmgXp1ZuNJso9QPpnfoRAQSaxkVijbYljOxz6FHaQqxSTMfrVdWGHsHqLveAbDAQmbsBVw6v5KSMXxSycZanA8djWGxpdaJYRlXyVfsg5bgqta+/db54Cwj2gowGGuC35cPxSqrB2Nt5OpWi/3xahP3YTGY9ZJOMx+nE2GVcqb3tPVS1/CV2mHtSWgrWNQSkCC5F72fi8lkh3c1N3El1ovNCWCJYIiaQ0b2kpbWaBI8z6lnS7bB7X3H2BfCWrkbKApZuzFmAVA9YDcDvSCloU/Oy2lVLVd3OhCmLmFDvJQJjehH8PkWLCl+qrDvMufnvOTBmyRkrWjc6M9uwxFvOIqWBx0ankxrRBaiIlzjt6XqhxuVkI2T0qTjuBfQWS8TH1uObXDzxDtXfcyLVZD13GSOlfBPc=
  file: "${TRAVIS_BUILD_DIR}/${SEEC_BUILT_XZ_FILENAME}"
  skip_cleanup: true
  on:
    tags: true
    repo: seec-team/seec-clang

