version: '4.0.0.{build}'

environment:
  LLVM_VERSION_STRING: '4.0.0'
  LLVM_BRANCH: 'release_40_appveyor'
  matrix:
  - COMPILER: msys2
    PLATFORM: x64
    MSYS2_DIR: msys64
    MSYSTEM: MINGW64

install:
  - '%APPVEYOR_BUILD_FOLDER%\scripts\appveyor\install.bat'

build_script:
  - '%APPVEYOR_BUILD_FOLDER%\scripts\appveyor\build.bat'

artifacts:
  - path: seec_clang_install_$(LLVM_VERSION_STRING).zip
